# ベースイメージを指定
FROM golang:1.23-alpine3.20 AS builder
# 必要なパッケージのインストール
RUN apk add --no-cache git

# ワーキングディレクトリを設定
WORKDIR /app

# Goモジュールを取得するためにgo.modとgo.sumをコピー
COPY go.mod go.sum ./
RUN go mod download

# ホットリロード用のコマンド
CMD ["go", "run", "main.go"]

# ポート8080を公開
EXPOSE 8080
